func_name: sigmoid
criterion_name: 'mae'
num_entries: 10
x_range: [-8.0, 8.0]
train: True
train_epochs: 40000
train_lr: 1.0e-3
weight_decay: 1.0e-4
prox_weight: 0.1
range_weight: 0.1
qat: True
bits: 10
qat_epochs: 5000
qat_lr: 1.0e-3